# The behavior of RuboCop can be controlled via the .rubocop.yml
# configuration file. It makes it possible to enable/disable
# certain cops (checks) and to alter their behavior if they accept
# any parameters. The file can be placed either in your home
# directory or in some project directory.
#
# RuboCop will start looking for the configuration file in the directory
# where the inspected file is and continue its way up to the root directory.
#
# See https://docs.rubocop.org/rubocop/configuration
plugins:
  - rubocop-rake
  - rubocop-rbs_inline
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable

Naming/AccessorMethodName:
  Exclude:
    - lib/ruboty/handlers/ai_agent.rb # we name handler methods from its word pattern

Naming/FileName:
  Exclude:
    - Steepfile

Layout/LineLength:
  Enabled: false

Layout/LeadingCommentSpace:
  AllowRBSInlineAnnotation: true
  AllowSteepAnnotation: true

Metrics:
  Enabled: false

RSpec/ExampleLength:
  Max: 7
  CountAsOne: ["array", "heredoc", "method_call"]

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/SpecFilePathFormat:
  CustomTransform:
    OpenAI: openai

Style/CommentedKeyword:
  Enabled: false # because of RBS annotations

Style/Documentation:
  AllowedConstants:
    - ClassMethods
    - PrependFeatures

Style/RedundantBegin:
  Enabled: false # because of Steep annotations
